In [1]:
import pandas as pd
import numpy as np

In [2]:
df =  pd.read_csv('./data/credit_card_balance.csv')
df = df.sort_values(['SK_ID_CURR','SK_ID_PREV','MONTHS_BALANCE'])
df.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'AMT_BALANCE',
       'AMT_CREDIT_LIMIT_ACTUAL', 'AMT_DRAWINGS_ATM_CURRENT',
       'AMT_DRAWINGS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT',
       'AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY',
       'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT',
       'AMT_RECEIVABLE_PRINCIPAL', 'AMT_RECIVABLE', 'AMT_TOTAL_RECEIVABLE',
       'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_CURRENT',
       'CNT_DRAWINGS_OTHER_CURRENT', 'CNT_DRAWINGS_POS_CURRENT',
       'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS', 'SK_DPD',
       'SK_DPD_DEF'],
      dtype='object')

In [3]:
# colfordummies = df.select_dtypes(include='object').columns

In [4]:
# df = pd.get_dummies(df, prefix=colfordummies)

In [5]:
# df=df[['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'AMT_BALANCE',
#        'AMT_CREDIT_LIMIT_ACTUAL','AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY',
#        'AMT_PAYMENT_CURRENT', 'SK_DPD']]
# df

In [6]:
# df['MONTHS_BALANCE'].unique()

In [7]:
df['AMT_DRAWINGS_POS_CURRENT'] = np.where((df['AMT_DRAWINGS_POS_CURRENT'].isna()) & (df['AMT_BALANCE']==0), 0, df['AMT_DRAWINGS_POS_CURRENT'] )
df['AMT_PAYMENT_CURRENT'] = np.where((df['AMT_PAYMENT_CURRENT'].isna()) & (df['AMT_BALANCE']==0), 0, df['AMT_PAYMENT_CURRENT'] )

In [8]:
df

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
1636141,1489396,100006,-6,0.000,270000,NaN,0.0,NaN,0.0,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
655566,1489396,100006,-5,0.000,270000,NaN,0.0,NaN,0.0,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1399895,1489396,100006,-4,0.000,270000,NaN,0.0,NaN,0.0,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
1347528,1489396,100006,-3,0.000,270000,NaN,0.0,NaN,0.0,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
520387,1489396,100006,-2,0.000,270000,NaN,0.0,NaN,0.0,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1437743,1794451,456250,-5,169443.855,180000,0.0,0.0,0.0,0.0,8931.420,...,169443.855,169443.855,0.0,0,0.0,0.0,6.0,Active,0,0
310299,1794451,456250,-4,166188.150,180000,0.0,0.0,0.0,0.0,8804.565,...,166188.150,166188.150,0.0,0,0.0,0.0,7.0,Active,0,0
1154348,1794451,456250,-3,162425.565,175500,0.0,0.0,0.0,0.0,8643.600,...,162425.565,162425.565,0.0,0,0.0,0.0,8.0,Active,0,0
1049726,1794451,456250,-2,158266.935,175500,0.0,0.0,0.0,0.0,8477.730,...,158266.935,158266.935,0.0,0,0.0,0.0,9.0,Active,0,0
140639,1794451,456250,-1,153832.725,175500,0.0,0.0,0.0,0.0,8286.390,...,153832.725,153832.725,0.0,0,0.0,0.0,10.0,Active,0,0

In [9]:
df['AMT_CREDIT_LIMIT_ACTUAL'] = df['AMT_CREDIT_LIMIT_ACTUAL'].replace(0,1)

In [10]:
df['SK_DPD_FARED_OF'] = df['SK_DPD']/-df['MONTHS_BALANCE']
df['PROPORTION_CREDIT_OVER_LIMIT_FARED_OF'] = df['AMT_DRAWINGS_POS_CURRENT']/df['AMT_CREDIT_LIMIT_ACTUAL']/-df['MONTHS_BALANCE']

In [11]:
df_summarized=df[['SK_ID_PREV','SK_ID_CURR', 'MONTHS_BALANCE','SK_DPD_FARED_OF','PROPORTION_CREDIT_OVER_LIMIT_FARED_OF']]

In [12]:
# df_summarized.groupby(['SK_ID_CURR']).agg({'SK_DPD_FARED_OF':'sum', 'PROPORTION_CREDIT_OVER_LIMIT_FARED_OF':'sum'})

In [13]:
# df.max()

In [14]:
df_summarized.to_csv('./treated_data/credit_card_balance.csv',index=False)